In [42]:
import pandas as pd
import ast

In [94]:
fd_data = pd.read_csv("fd_results_8b_api.csv")

In [ ]:
fd_data.head()

,tag,image_name,true_description,description_for_answer,description_for_question,false_source_image_name,generated_question,used_prompt,model_output
0,false_detail,882048099.jpg,A woman in a blue bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,882048099.jpg,What color is the bathing suit the woman is we...,In the picture A woman in a gray bathing suit...,"[blue, 95]"
1,false_detail,199413509.jpg,A woman peers out from her halfway opened blu...,A man peers out from her halfway opened blue ...,A man peers out from her halfway opened blue ...,199413509.jpg,What gender is the person peering out from the...,In the picture A man peers out from her halfw...,"[man, 95]"
2,false_detail,2825540754.jpg,a little boy is running on the beach with a r...,a little boy is running on the beach with a g...,a little boy is running on the beach with a g...,2825540754.jpg,What color is the bucket the boy is holding?,In the picture a little boy is running on the...,"[red, 100]"
3,false_detail,4850944716.jpg,an older man wearing a suit has his arms fold...,an older woman wearing a suit has his arms fo...,an older woman wearing a suit has his arms fo...,4850944716.jpg,What gender is the person wearing the suit?,In the picture an older woman wearing a suit ...,"[""male"", 95]"
4,false_detail,4526883901.jpg,"A white-haired man with glasses , wearing a g...","A white-haired woman with glasses , wearing a...","A white-haired woman with glasses , wearing a...",4526883901.jpg,What is the gender of the person working on th...,In the picture A white-haired woman with glas...,"[woman, 100]"

In [95]:
fd_data["model_answer"] = None
fd_data["verb_confidence"] = None
for i in fd_data.index:
  output = fd_data.at[i, "model_output"][1:-1].split(", ")
  try:
    fd_data.at[i, "model_answer"] = output[0].lower()
    fd_data.at[i, "verb_confidence"] = output[1].lower()
  except:
    fd_data.at[i, "model_answer"] = "Invalid output"
    fd_data.at[i, "verb_confidence"] = "Invalid output"

In [96]:
fd_data["model_answer"] = (
    fd_data["model_answer"]
    .astype(str)
    .str.strip("'\"")
    .str.strip()
    .str.lower()
)

In [97]:
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='man', value='male')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='woman', value='female')

In [98]:
fd_data["model_answer"].unique()

array(['blue', 'male', 'red', 'female', 'unknown', 'men', 'white',
       'green', 'off-black', 'yellow', 'black', 'gray', '0', 'orange',
       'golden', 'blond', 'pink', 'purple', '["male"]', 'light brown',
       'black and tan', '["yellow"]', 'brown', '["violet',
       '["brown and tan"]', '["purple', '["brown"]', '["pink"]',
       '["female', 'black and fuchsia'], dtype=object)

In [99]:
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='men', value='male')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='light brown', value='brown')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='black and tan', value='black')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["brown"]', value='brown')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["pink"]', value='pink')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["female', value='female')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["purple', value='purple')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["violet', value='violet')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["yellow"]', value='yellow')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='off-black', value='black')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='black and fuchsia', value='black')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["brown and tan"]', value='brown')
fd_data["model_answer"] = fd_data["model_answer"].replace(to_replace='["male"]', value='male')

In [100]:
fd_data["model_answer"].unique()

array(['blue', 'male', 'red', 'female', 'unknown', 'white', 'green',
       'black', 'yellow', 'gray', '0', 'orange', 'golden', 'blond',
       'pink', 'purple', 'brown', 'violet'], dtype=object)

In [101]:
fd_data["verb_confidence"].unique()

array(['95', '100', '30', '0', '90', '85', '50', '100]', '95]',
       '"female"]'], dtype=object)

In [102]:
fd_data["verb_confidence"] = fd_data["verb_confidence"].replace(to_replace='"female"]', value='100')
fd_data["verb_confidence"] = fd_data["verb_confidence"].replace(to_replace='100]', value='100')

In [103]:
fd_data["verb_confidence"].unique()

array(['95', '100', '30', '0', '90', '85', '50', '95]'], dtype=object)

In [104]:
fd_data[["image_name","model_answer"]]

         image_name model_answer
0     882048099.jpg         blue
1     199413509.jpg         male
2    2825540754.jpg          red
3    4850944716.jpg         male
4    4526883901.jpg       female
..              ...          ...
295   787907341.jpg         male
296  2735517817.jpg         male
297  2211495714.jpg        white
298   363394643.jpg       purple
299  4078113886.jpg       female

[300 rows x 2 columns]

In [106]:
fd_answers = pd.read_csv("db_false_detail.csv")

In [ ]:
fd_answers.head()

,image_name,true_caption,false_caption,edit_type,old_value,new_value
0,882048099.jpg,A woman in a blue bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,color,blue,gray
1,199413509.jpg,A woman peers out from her halfway opened blu...,A man peers out from her halfway opened blue ...,gender,woman,man
2,2825540754.jpg,a little boy is running on the beach with a r...,a little boy is running on the beach with a g...,color,red,green
3,4850944716.jpg,an older man wearing a suit has his arms fold...,an older woman wearing a suit has his arms fo...,gender,man,woman
4,4526883901.jpg,"A white-haired man with glasses , wearing a g...","A white-haired woman with glasses , wearing a...",gender,man,woman

In [107]:
fd_answers["edit_type"].value_counts()

edit_type
gender    166
color     134
Name: count, dtype: int64

In [108]:
fd_data = pd.concat([fd_data, fd_answers[["edit_type", "old_value", "new_value"]]], axis=1)

In [ ]:
fd_data.head()

,tag,image_name,true_description,description_for_answer,description_for_question,false_source_image_name,generated_question,used_prompt,model_output,output_probs,model_answer,verb_confidence,int_confidence,edit_type,old_value,new_value
0,false_detail,882048099.jpg,A woman in a blue bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,882048099.jpg,What color is the bathing suit the woman is we...,You are given two descriptions of the same ima...,"['gray', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",grey,95,None,color,blue,gray
1,false_detail,199413509.jpg,A woman peers out from her halfway opened blu...,A man peers out from her halfway opened blue ...,A man peers out from her halfway opened blue ...,199413509.jpg,What gender is the person peering out from the...,You are given two descriptions of the same ima...,"['male', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",male,95,1.0,gender,woman,man
2,false_detail,2825540754.jpg,a little boy is running on the beach with a r...,a little boy is running on the beach with a g...,a little boy is running on the beach with a g...,2825540754.jpg,What color is the bucket the boy is holding?,You are given two descriptions of the same ima...,"['red', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",red,95,1.0,color,red,green
3,false_detail,4850944716.jpg,an older man wearing a suit has his arms fold...,an older woman wearing a suit has his arms fo...,an older woman wearing a suit has his arms fo...,4850944716.jpg,What gender is the person wearing the suit?,You are given two descriptions of the same ima...,"['male', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",male,95,1.0,gender,man,woman
4,false_detail,4526883901.jpg,"A white-haired man with glasses , wearing a g...","A white-haired woman with glasses , wearing a...","A white-haired woman with glasses , wearing a...",4526883901.jpg,What is the gender of the person working on th...,You are given two descriptions of the same ima...,"['male', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",male,95,1.0,gender,man,woman

In [109]:
fd_data["old_value"].value_counts()

old_value
man       81
woman     52
blue      33
white     24
men       23
red       18
black     18
brown     13
green     10
women     10
yellow     7
purple     4
pink       4
orange     2
gray       1
Name: count, dtype: int64

In [112]:
fd_data["new_value"].value_counts()

new_value
woman     81
man       52
women     23
orange    15
gray      14
black     14
grey      14
white     11
yellow    10
men       10
brown     10
violet     9
green      9
blue       9
red        8
purple     6
pink       5
Name: count, dtype: int64

In [113]:
fd_data["old_value"] = fd_data["old_value"].replace(to_replace="grey", value='gray')
fd_data["new_value"] = fd_data["new_value"].replace(to_replace="grey", value='gray')
fd_data["old_value"] = fd_data["old_value"].replace(to_replace="woman", value='female')
fd_data["new_value"] = fd_data["new_value"].replace(to_replace="woman", value='female')
fd_data["old_value"] = fd_data["old_value"].replace(to_replace="man", value='male')
fd_data["new_value"] = fd_data["new_value"].replace(to_replace="man", value='male')

In [114]:
fd_data["old_value"] = fd_data["old_value"].replace(to_replace="men", value='male')
fd_data["new_value"] = fd_data["new_value"].replace(to_replace="men", value='male')
fd_data["old_value"] = fd_data["old_value"].replace(to_replace="women", value='female')
fd_data["new_value"] = fd_data["new_value"].replace(to_replace="women", value='female')

In [115]:
# опора на картинку
general_accuracy = (fd_data["model_answer"] == fd_data["old_value"]).mean()
general_accuracy

np.float64(0.7766666666666666)

In [116]:
# опора на картинку гендер
gender_df = fd_data[fd_data["edit_type"] == "gender"]

gender_accuracy = (gender_df["model_answer"] == gender_df["old_value"]).mean()
gender_accuracy

np.float64(0.8313253012048193)

In [117]:
# опора на картинку цвет
color_df = fd_data[fd_data["edit_type"] == "color"]

color_accuracy = (color_df["model_answer"] == color_df["old_value"]).mean()
color_accuracy

np.float64(0.7089552238805971)

In [ ]:
fd_data.head()

,tag,image_name,true_description,description_for_answer,description_for_question,false_source_image_name,generated_question,used_prompt,model_output,output_probs,model_answer,verb_confidence,int_confidence,edit_type,old_value,new_value
0,false_detail,882048099.jpg,A woman in a blue bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,A woman in a gray bathing suit and straw hat ...,882048099.jpg,What color is the bathing suit the woman is we...,You are given two descriptions of the same ima...,"['gray', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",grey,95,NaN,color,blue,grey
1,false_detail,199413509.jpg,A woman peers out from her halfway opened blu...,A man peers out from her halfway opened blue ...,A man peers out from her halfway opened blue ...,199413509.jpg,What gender is the person peering out from the...,You are given two descriptions of the same ima...,"['male', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",male,95,100.0,gender,female,male
2,false_detail,2825540754.jpg,a little boy is running on the beach with a r...,a little boy is running on the beach with a g...,a little boy is running on the beach with a g...,2825540754.jpg,What color is the bucket the boy is holding?,You are given two descriptions of the same ima...,"['red', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",red,95,100.0,color,red,green
3,false_detail,4850944716.jpg,an older man wearing a suit has his arms fold...,an older woman wearing a suit has his arms fo...,an older woman wearing a suit has his arms fo...,4850944716.jpg,What gender is the person wearing the suit?,You are given two descriptions of the same ima...,"['male', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",male,95,100.0,gender,male,female
4,false_detail,4526883901.jpg,"A white-haired man with glasses , wearing a g...","A white-haired woman with glasses , wearing a...","A white-haired woman with glasses , wearing a...",4526883901.jpg,What is the gender of the person working on th...,You are given two descriptions of the same ima...,"['male', 95]","[[([', 1.000000), (#, 0.000000), (!, 0.000000)...",male,95,100.0,gender,male,female

In [118]:
# количество ответов по картинке
(fd_data["model_answer"] == fd_data["old_value"]).sum()

np.int64(233)

In [119]:
# количество ответов по тексту
(fd_data["model_answer"] == fd_data["new_value"]).sum()

np.int64(49)

In [120]:
# ответ неправильный ни по картинке, ни по тексту
len(fd_data) - 233 - 49

18

In [121]:
# опиралась на картинку
233/len(fd_data)

0.7766666666666666

In [122]:
# опиралась на текст
49/len(fd_data)

0.16333333333333333

In [123]:
18/len(fd_data)

0.06